CH-174831358-Integrate-Linter
leickon/data-api pull request #1
Opened 2020-09-16 07:12 UTC by developerbello

## Description

Ticket - [174831358](https://www.pivotaltracker.com/n/projects/2466055/stories/174831358)

- Integrate Linter with [Eslint](https://eslint.org/)

## Additional Changes

- Added `.eslintrc.json` as Eslint conguration file
- installed Eslint npm package using `yarn add eslint` 
- Installed Eslint npm packages such as `eslint-plugin-import` and `eslint-watch` for additional options to the linter
- Added npm script add calls eslint `esw --watch dir`
- We can run able our linter using `yarn run eslint`

2020-09-16 13:05 UTC, abdulfataiaka commented
Please follow the requirements on the Ticket to complete expectations, thanks

2020-09-16 13:38 UTC, developerbello commented
> Please follow the requirements on the Ticket to complete expectations, thanks

Ok, I will ensure to follow instructions based on the requirements. Thanks

2020-09-18 21:11 UTC, abdulfataiaka requested changes

2020-09-18 21:11 UTC, abdulfataiaka commented on .eslintrc.json
> +    "mongo": true
Remove mongo and browser env since we are not running the code on the browser

2020-09-18 21:11 UTC, abdulfataiaka commented on package.json
> +    "eslint": "esw --watch app api"
We do not need to watch for changes as that might eat up the memory. We should only be able to run eslint to see errors or warning whenever we need to. `yarn eslint`

Also, we can configure VSCode to do the watching for us

2020-09-18 21:19 UTC, abdulfataiaka commented on package.json
> +    "eslint": "esw --watch app api"
Rename the script `eslint` to `lint`

2020-09-18 22:04 UTC, developerbello commented on .eslintrc.json
> +    "mongo": true
Added changes as required

2020-09-18 22:04 UTC, developerbello commented on package.json
> +    "eslint": "esw --watch app api"
Added changes as required

2020-09-19 22:55 UTC, abdulfataiaka approved these changes

2020-09-20 00:32 UTC, merged